version: "3.9"
services:
  postgres-0:
    container_name: postgres-0
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      # Place startup .sql files here. They are executed in alphabetical order
      # on service start.
      - ./dbScripts:/docker-entrypoint-initdb.d/
      # Mount data volume in local system in order to keep data between
      # container calls.
      - ./dbData:/var/lib/postgresql/data
  shortener:
    container_name: shortener-0
    image: shortener
    restart: unless-stopped
    environment:
      - DB_URL=jdbc:postgresql://192.168.1.65:5433/url_shortener
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '8080:8080'